# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import user_pb2 as protos_dot_user__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignUp = channel.unary_unary(
                '/userservice.UserService/SignUp',
                request_serializer=protos_dot_user__pb2.SignupUser.SerializeToString,
                response_deserializer=protos_dot_user__pb2.UsersResponse.FromString,
                _registered_method=True)
        self.CreateOrganization = channel.unary_unary(
                '/userservice.UserService/CreateOrganization',
                request_serializer=protos_dot_user__pb2.CreateOrganizationRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.CreateOrganizationResponse.FromString,
                _registered_method=True)
        self.UpdateOrganization = channel.unary_unary(
                '/userservice.UserService/UpdateOrganization',
                request_serializer=protos_dot_user__pb2.UpdateOrganizationRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.ViewOrganization = channel.unary_unary(
                '/userservice.UserService/ViewOrganization',
                request_serializer=protos_dot_user__pb2.ViewOrganizationRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ViewOrganizationResponse.FromString,
                _registered_method=True)
        self.DeleteOrganization = channel.unary_unary(
                '/userservice.UserService/DeleteOrganization',
                request_serializer=protos_dot_user__pb2.DeleteOrganizationRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/userservice.UserService/UpdateProfile',
                request_serializer=protos_dot_user__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.UpdateEmail = channel.unary_unary(
                '/userservice.UserService/UpdateEmail',
                request_serializer=protos_dot_user__pb2.UpdateEmailRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.UpdatePassword = channel.unary_unary(
                '/userservice.UserService/UpdatePassword',
                request_serializer=protos_dot_user__pb2.UpdatePasswordRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/userservice.UserService/DeleteUser',
                request_serializer=protos_dot_user__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.ChangeProfilePicture = channel.unary_unary(
                '/userservice.UserService/ChangeProfilePicture',
                request_serializer=protos_dot_user__pb2.ChangeProfilePictureRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.SocialSignUp = channel.unary_unary(
                '/userservice.UserService/SocialSignUp',
                request_serializer=protos_dot_user__pb2.SocialUser.SerializeToString,
                response_deserializer=protos_dot_user__pb2.UsersResponse.FromString,
                _registered_method=True)
        self.VerifyInvitation = channel.unary_unary(
                '/userservice.UserService/VerifyInvitation',
                request_serializer=protos_dot_user__pb2.VerifyInvitationReq.SerializeToString,
                response_deserializer=protos_dot_user__pb2.VerifyInvitationRes.FromString,
                _registered_method=True)
        self.SignIn = channel.unary_unary(
                '/userservice.UserService/SignIn',
                request_serializer=protos_dot_user__pb2.SignInReq.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.DisplayUser = channel.unary_unary(
                '/userservice.UserService/DisplayUser',
                request_serializer=protos_dot_user__pb2.DisplayUserRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.DisplayUserResponse.FromString,
                _registered_method=True)
        self.RemoveUser = channel.unary_unary(
                '/userservice.UserService/RemoveUser',
                request_serializer=protos_dot_user__pb2.RemoveUserRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.RemoveService = channel.unary_unary(
                '/userservice.UserService/RemoveService',
                request_serializer=protos_dot_user__pb2.RemoveServiceRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.AssignService = channel.unary_unary(
                '/userservice.UserService/AssignService',
                request_serializer=protos_dot_user__pb2.AssignServiceRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.UpdateOrganizationRole = channel.unary_unary(
                '/userservice.UserService/UpdateOrganizationRole',
                request_serializer=protos_dot_user__pb2.UpdateOrganizationRoleRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.UpdateServiceRole = channel.unary_unary(
                '/userservice.UserService/UpdateServiceRole',
                request_serializer=protos_dot_user__pb2.UpdateServiceRoleRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.ViewProfile = channel.unary_unary(
                '/userservice.UserService/ViewProfile',
                request_serializer=protos_dot_user__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ViewProfileResponse.FromString,
                _registered_method=True)
        self.CreateInvitation = channel.unary_unary(
                '/userservice.UserService/CreateInvitation',
                request_serializer=protos_dot_user__pb2.CreateInvitationRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.DisplayInvitation = channel.unary_unary(
                '/userservice.UserService/DisplayInvitation',
                request_serializer=protos_dot_user__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_user__pb2.DisplayInvitationResponse.FromString,
                _registered_method=True)
        self.DeleteInvitation = channel.unary_unary(
                '/userservice.UserService/DeleteInvitation',
                request_serializer=protos_dot_user__pb2.DeleteInvitationRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.ResetPassword = channel.unary_unary(
                '/userservice.UserService/ResetPassword',
                request_serializer=protos_dot_user__pb2.ResetPasswordReq.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.ForgotPassword = channel.unary_unary(
                '/userservice.UserService/ForgotPassword',
                request_serializer=protos_dot_user__pb2.ForgotPasswordReq.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.SetPassword = channel.unary_unary(
                '/userservice.UserService/SetPassword',
                request_serializer=protos_dot_user__pb2.ResetPasswordReq.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.ChangePassword = channel.unary_unary(
                '/userservice.UserService/ChangePassword',
                request_serializer=protos_dot_user__pb2.ChangePasswordReq.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.VerifyUser = channel.unary_unary(
                '/userservice.UserService/VerifyUser',
                request_serializer=protos_dot_user__pb2.VerifyUserRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.VerifyEmail = channel.unary_unary(
                '/userservice.UserService/VerifyEmail',
                request_serializer=protos_dot_user__pb2.VerifyEmailRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.Services = channel.unary_unary(
                '/userservice.UserService/Services',
                request_serializer=protos_dot_user__pb2.EmptyRequest.SerializeToString,
                response_deserializer=protos_dot_user__pb2.ServicesResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SignUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeProfilePicture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SocialSignUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyInvitation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrganizationRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateServiceRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInvitation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayInvitation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInvitation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForgotPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Services(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignUp': grpc.unary_unary_rpc_method_handler(
                    servicer.SignUp,
                    request_deserializer=protos_dot_user__pb2.SignupUser.FromString,
                    response_serializer=protos_dot_user__pb2.UsersResponse.SerializeToString,
            ),
            'CreateOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrganization,
                    request_deserializer=protos_dot_user__pb2.CreateOrganizationRequest.FromString,
                    response_serializer=protos_dot_user__pb2.CreateOrganizationResponse.SerializeToString,
            ),
            'UpdateOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrganization,
                    request_deserializer=protos_dot_user__pb2.UpdateOrganizationRequest.FromString,
                    response_serializer=protos_dot_user__pb2.MessageResponse.SerializeToString,
            ),
            'ViewOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewOrganization,
                    request_deserializer=protos_dot_user__pb2.ViewOrganizationRequest.FromString,
                    response_serializer=protos_dot_user__pb2.ViewOrganizationResponse.SerializeToString,
            ),
            'DeleteOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteOrganization,
                    request_deserializer=protos_dot_user__pb2.DeleteOrganizationRequest.FromString,
                    response_serializer=protos_dot_user__pb2.MessageResponse.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=protos_dot_user__pb2.UpdateProfileRequest.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'UpdateEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEmail,
                    request_deserializer=protos_dot_user__pb2.UpdateEmailRequest.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'UpdatePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePassword,
                    request_deserializer=protos_dot_user__pb2.UpdatePasswordRequest.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=protos_dot_user__pb2.DeleteUserRequest.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'ChangeProfilePicture': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeProfilePicture,
                    request_deserializer=protos_dot_user__pb2.ChangeProfilePictureRequest.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'SocialSignUp': grpc.unary_unary_rpc_method_handler(
                    servicer.SocialSignUp,
                    request_deserializer=protos_dot_user__pb2.SocialUser.FromString,
                    response_serializer=protos_dot_user__pb2.UsersResponse.SerializeToString,
            ),
            'VerifyInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyInvitation,
                    request_deserializer=protos_dot_user__pb2.VerifyInvitationReq.FromString,
                    response_serializer=protos_dot_user__pb2.VerifyInvitationRes.SerializeToString,
            ),
            'SignIn': grpc.unary_unary_rpc_method_handler(
                    servicer.SignIn,
                    request_deserializer=protos_dot_user__pb2.SignInReq.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'DisplayUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayUser,
                    request_deserializer=protos_dot_user__pb2.DisplayUserRequest.FromString,
                    response_serializer=protos_dot_user__pb2.DisplayUserResponse.SerializeToString,
            ),
            'RemoveUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUser,
                    request_deserializer=protos_dot_user__pb2.RemoveUserRequest.FromString,
                    response_serializer=protos_dot_user__pb2.MessageResponse.SerializeToString,
            ),
            'RemoveService': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveService,
                    request_deserializer=protos_dot_user__pb2.RemoveServiceRequest.FromString,
                    response_serializer=protos_dot_user__pb2.MessageResponse.SerializeToString,
            ),
            'AssignService': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignService,
                    request_deserializer=protos_dot_user__pb2.AssignServiceRequest.FromString,
                    response_serializer=protos_dot_user__pb2.MessageResponse.SerializeToString,
            ),
            'UpdateOrganizationRole': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrganizationRole,
                    request_deserializer=protos_dot_user__pb2.UpdateOrganizationRoleRequest.FromString,
                    response_serializer=protos_dot_user__pb2.MessageResponse.SerializeToString,
            ),
            'UpdateServiceRole': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateServiceRole,
                    request_deserializer=protos_dot_user__pb2.UpdateServiceRoleRequest.FromString,
                    response_serializer=protos_dot_user__pb2.MessageResponse.SerializeToString,
            ),
            'ViewProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewProfile,
                    request_deserializer=protos_dot_user__pb2.Empty.FromString,
                    response_serializer=protos_dot_user__pb2.ViewProfileResponse.SerializeToString,
            ),
            'CreateInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInvitation,
                    request_deserializer=protos_dot_user__pb2.CreateInvitationRequest.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'DisplayInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayInvitation,
                    request_deserializer=protos_dot_user__pb2.Empty.FromString,
                    response_serializer=protos_dot_user__pb2.DisplayInvitationResponse.SerializeToString,
            ),
            'DeleteInvitation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInvitation,
                    request_deserializer=protos_dot_user__pb2.DeleteInvitationRequest.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'ResetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPassword,
                    request_deserializer=protos_dot_user__pb2.ResetPasswordReq.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'ForgotPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ForgotPassword,
                    request_deserializer=protos_dot_user__pb2.ForgotPasswordReq.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'SetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPassword,
                    request_deserializer=protos_dot_user__pb2.ResetPasswordReq.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'ChangePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePassword,
                    request_deserializer=protos_dot_user__pb2.ChangePasswordReq.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'VerifyUser': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyUser,
                    request_deserializer=protos_dot_user__pb2.VerifyUserRequest.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'VerifyEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyEmail,
                    request_deserializer=protos_dot_user__pb2.VerifyEmailRequest.FromString,
                    response_serializer=protos_dot_user__pb2.ActionResponse.SerializeToString,
            ),
            'Services': grpc.unary_unary_rpc_method_handler(
                    servicer.Services,
                    request_deserializer=protos_dot_user__pb2.EmptyRequest.FromString,
                    response_serializer=protos_dot_user__pb2.ServicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'userservice.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('userservice.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/SignUp',
            protos_dot_user__pb2.SignupUser.SerializeToString,
            protos_dot_user__pb2.UsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/CreateOrganization',
            protos_dot_user__pb2.CreateOrganizationRequest.SerializeToString,
            protos_dot_user__pb2.CreateOrganizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/UpdateOrganization',
            protos_dot_user__pb2.UpdateOrganizationRequest.SerializeToString,
            protos_dot_user__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/ViewOrganization',
            protos_dot_user__pb2.ViewOrganizationRequest.SerializeToString,
            protos_dot_user__pb2.ViewOrganizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/DeleteOrganization',
            protos_dot_user__pb2.DeleteOrganizationRequest.SerializeToString,
            protos_dot_user__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/UpdateProfile',
            protos_dot_user__pb2.UpdateProfileRequest.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/UpdateEmail',
            protos_dot_user__pb2.UpdateEmailRequest.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/UpdatePassword',
            protos_dot_user__pb2.UpdatePasswordRequest.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/DeleteUser',
            protos_dot_user__pb2.DeleteUserRequest.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeProfilePicture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/ChangeProfilePicture',
            protos_dot_user__pb2.ChangeProfilePictureRequest.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SocialSignUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/SocialSignUp',
            protos_dot_user__pb2.SocialUser.SerializeToString,
            protos_dot_user__pb2.UsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/VerifyInvitation',
            protos_dot_user__pb2.VerifyInvitationReq.SerializeToString,
            protos_dot_user__pb2.VerifyInvitationRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/SignIn',
            protos_dot_user__pb2.SignInReq.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisplayUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/DisplayUser',
            protos_dot_user__pb2.DisplayUserRequest.SerializeToString,
            protos_dot_user__pb2.DisplayUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/RemoveUser',
            protos_dot_user__pb2.RemoveUserRequest.SerializeToString,
            protos_dot_user__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/RemoveService',
            protos_dot_user__pb2.RemoveServiceRequest.SerializeToString,
            protos_dot_user__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/AssignService',
            protos_dot_user__pb2.AssignServiceRequest.SerializeToString,
            protos_dot_user__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrganizationRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/UpdateOrganizationRole',
            protos_dot_user__pb2.UpdateOrganizationRoleRequest.SerializeToString,
            protos_dot_user__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateServiceRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/UpdateServiceRole',
            protos_dot_user__pb2.UpdateServiceRoleRequest.SerializeToString,
            protos_dot_user__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/ViewProfile',
            protos_dot_user__pb2.Empty.SerializeToString,
            protos_dot_user__pb2.ViewProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/CreateInvitation',
            protos_dot_user__pb2.CreateInvitationRequest.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisplayInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/DisplayInvitation',
            protos_dot_user__pb2.Empty.SerializeToString,
            protos_dot_user__pb2.DisplayInvitationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteInvitation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/DeleteInvitation',
            protos_dot_user__pb2.DeleteInvitationRequest.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/ResetPassword',
            protos_dot_user__pb2.ResetPasswordReq.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForgotPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/ForgotPassword',
            protos_dot_user__pb2.ForgotPasswordReq.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/SetPassword',
            protos_dot_user__pb2.ResetPasswordReq.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/ChangePassword',
            protos_dot_user__pb2.ChangePasswordReq.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/VerifyUser',
            protos_dot_user__pb2.VerifyUserRequest.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/VerifyEmail',
            protos_dot_user__pb2.VerifyEmailRequest.SerializeToString,
            protos_dot_user__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Services(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserService/Services',
            protos_dot_user__pb2.EmptyRequest.SerializeToString,
            protos_dot_user__pb2.ServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
